---
title: "Complaints6-9"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(primer.data)
library(ggplot2)
library(plotly)
raw_data <- read_csv("https://raw.githubusercontent.com/Financial-Times/police-misconduct-complaints-analysis/main/output/philly_clean.csv") %>% 
  select(officer_id, po_race, po_sex)
```

```{r}
raw_data %>% 
  group_by(officer_id) %>% 
  summarise(total = n()) %>% 
  mutate(officer_id = as.character(officer_id)) %>%
  mutate(compl_dec = ntile(x = total, 10)) %>%
  group_by(compl_dec) %>%
  summarize(compl_total = sum(total)) %>%
  mutate(compl_percentage = compl_total/sum(compl_total)) %>%
  ggplot(aes(x = compl_dec, y = compl_percentage)) +
    geom_col(fill = "brown") + theme_gray() + 
    scale_x_continuous(breaks = c(1:10)) + 
    scale_y_continuous(labels = scales::percent_format()) +
    labs(title = "Complaint numbers for each decile of officers",
         subtitle = "Top 10% of Officers has a third of police complaints",
         x = "Deciles of officers",
         y = NULL,
         caption = "Source: Financial Times")
  
```





